"""모델 피처에 사용할 수 있는 공식 원천 검증 상태의 단일 계약."""

DART_STRUCTURAL_AGGREGATE_STATUS = "verified_dart_structural_aggregate_v1"
OFFICIAL_UNDERWRITER_AGGREGATE_STATUS = "verified_official_underwriter_aggregate_v1"
KRX_UNDERWRITER_TIER_STATUS = "verified_krx_underwriter_registry_mapping_v1"
DART_PUBLIC_FLOAT_STATUS = "verified_dart_public_float_direct_v1"
DART_OFFERING_STRUCTURE_STATUS = "verified_dart_offering_structure_v1"

APPROVED_INSTITUTIONAL_DEMAND_STATUSES = frozenset({
    DART_STRUCTURAL_AGGREGATE_STATUS,
    OFFICIAL_UNDERWRITER_AGGREGATE_STATUS,
})
APPROVED_LOCKUP_STATUSES = APPROVED_INSTITUTIONAL_DEMAND_STATUSES
APPROVED_UNDERWRITER_TIER_STATUSES = frozenset({KRX_UNDERWRITER_TIER_STATUS})
APPROVED_PUBLIC_FLOAT_STATUSES = frozenset({DART_PUBLIC_FLOAT_STATUS})
APPROVED_OFFERING_STRUCTURE_STATUSES = frozenset({DART_OFFERING_STRUCTURE_STATUS})
